without validate-branch-name

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,5 +1,14 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npx validate-branch-name $1
+BRANCH_NAME=$(git symbolic-ref --short HEAD)
+BRANCH_PATTERN="^(feature|test|release)\/HNJ-[0-9]+_[a-zA-Z0-9-]+$"
+
+if [[ ! "$BRANCH_NAME" =~ $BRANCH_PATTERN ]]; then
+  echo "Invalid branch name format. Branch name should be in the format of <ticket type>/EVWSNX-<number>_<description>"
+  exit 1
+else
+    echo "Branch name is valid"
+fi
+
 npm run test;
